### ISSUE TITLE
Parameter Adress

### ISSUE THREAD

**Issue by TrolLlock** [Nekromateion/RedGifs-Gfycat-Downloader#11]
Hey, since last update im getting this error. Username and filepath changed to X
x:\x\RedGifs_Rewrite_DNCore_x64>.\RedGifs_Rewrite_DNCore_x64.exe --type=GIF --user=x
Downloading user xxx...
System.ArgumentNullException: Value cannot be null. (Parameter 'address')
   at System.Net.WebClient.GetUri(String address)
   at GfycatDownloader_Rewrite_DNCore.RedGifs.DownloadUser(String userId, String type, Int32 minLikes)
   at GfycatDownloader_Rewrite_DNCore.Program.Main(String[] args)

Yes im trying to run it like a CLI/Bat file.
What is this Adress its asking for? is that the folder i wish to save it to or the user adress which seems unneccesary since it clearly found the user itself. (if folder how is it interpreted?)
This is not atleast as far as ive found not written in the Readme or in the CLI section of the download.
Kind Regards

**Comment by Nekromateion** [comment]
Hey there,
I recently found out that [Gallery-DL](https://github.com/mikf/gallery-dl) supports redgifs so please use that, since I don't have the time to maintain this project anymore.
