### ISSUE TITLE
is it possible to make a gfycat version of this?

### ISSUE THREAD

**Issue by airfathaaaaa** [Nekromateion/RedGifs-Gfycat-Downloader#3]

**Comment by Nekromateion** [comment]
I doubt that it's possible since they have a more locked down API than redgifs if i remember correctly.
I will look into it and at least try though.

**Comment by airfathaaaaa** [comment]
thank you i tried but i soon discovered that my skills are not about programming what so ever lol

**Comment by Nekromateion** [comment]
Okay, finally had the chance to look into it a bit and from what I saw so far I should be able to do it.
I'll reply to this again with a link to the repo of it.

**Comment by Nekromateion** [comment]
Scrap that I found out that it's way easier than that so I just changed this one up a bit.
Implemented it in version 0.4
Enjoy!

**Comment by airfathaaaaa** [comment]
sir you are a genious! thank you very much for your time
