### ISSUE TITLE
can't find exe file

### ISSUE THREAD

**Issue by JackLamber** [Nekromateion/RedGifs-Gfycat-Downloader#4]
I'm sorry I know nothing about coding, but I can't find the exe file anywhere

**Comment by Nekromateion** [comment]
You can find it under "Releases"
![image](https://user-images.githubusercontent.com/43814053/124515977-05d29900-dde1-11eb-96d1-ecef7b26f59e.png)

https://github.com/Nekromateion/RedGifs-Gfycat-Downloader/releases/tag/0.4

**Comment by JackLamber** [comment]
Thank you very much Sir/Ma'am. Is there a way to change the download directory?
Thank you for the work

**Comment by Nekromateion** [comment]
At the moment there isn't it downloads to the same directory the exe is in.
However I can add a option to change the download directory. (I'll add it in the next update and msg here again when it's added)

**Comment by JackLamber** [comment]
I was a bit confused because the first time I tried to download it directed the folder to IDM's app data folder (C:\Users\MYPC\AppData\Roaming\IDM) which is weird because the exe wasn't even there.
Now it's working fine. Thanks again
