### ISSUE TITLE
command options?

### ISSUE THREAD

**Issue by KatieWebb** [Nekromateion/RedGifs-Gfycat-Downloader#5]
This is a great program. Very... useful...

Are there command line options if I open this with a bat file?
for example,

RedGifsDownloader.exe  --Type 1/2 --id/search [username] --format mp4/gif --minlikes 13

**Comment by Nekromateion** [comment]
No there are not.
Well at least not yet.
I'll add that when I'm back from my trip on the 4.8.

**Comment by Nekromateion** [comment]
I implemented this in a really sloppy way but it should be fine.
https://github.com/Nekromateion/RedGifs-Gfycat-Downloader/releases/tag/0.5

**Comment by KatieWebb** [comment]
Awesome! Tried it and it's working! This makes my life easier!

Thanks!
