### ISSUE TITLE
Gfycat or Redgifs returning (404) and not downloading content

### ISSUE THREAD

**Issue by diffficult** [Nekromateion/RedGifs-Gfycat-Downloader#6]
Latest version available on the Releases page.

Was working fine on Windows 10 and even on Linux using `wine GfycatDownloader.exe` to run it, but lately started to fail on redgifs with this type of output. 

```
System.Net.WebException: The remote server returned an error: (404) Not Found.
  at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellati
onToken) [0x00146] in <546f3de1e5a24a2fadcc0d4150fcc018>:0 
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, Syste
m.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <546f3de1e5a24a2fadcc0d4150
fcc018>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00016] in <546f3de1e5a24a2fadcc0d4150fcc018>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <546f3de1e5a24a2fadcc0d4150fcc018>:0 
  at System.Net.WebClient.DownloadBits (System.Net.WebRequest request, System.IO.Stream writeStream) [0x000e6] in <546f3de1e5a24a2fadc
c0d4150fcc018>:0 
  at System.Net.WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request) [0x00061] in <546f3de1e5a24a2fadcc
0d4150fcc018>:0 
  at System.Net.WebClient.DownloadString (System.Uri address) [0x00011] in <546f3de1e5a24a2fadcc0d4150fcc018>:0 
  at System.Net.WebClient.DownloadString (System.String address) [0x00008] in <546f3de1e5a24a2fadcc0d4150fcc018>:0 
  at (wrapper remoting-invoke-with-check) System.Net.WebClient.DownloadString(string)
  at RedGifsDownloader.Api.DownloadUser (System.String userId, System.Boolean downloadMp4, System.Int32 minLikes) [0x00024] in <d24c72
0d1d7f47df8e263014f0542758>:0 
  at RedGifsDownloader.Program.Main (System.String[] args) [0x001d9] in <d24c720d1d7f47df8e263014f0542758>:0 
DOWNLOAD FINISHED!

```

**Comment by Nekromateion** [comment]
Are you sure you selected the right service(redgifs when downloading from redgifs and gfycat when downloading from gfycat) and that you gave it the correct id (removed the @ when downloading from gfycat) or was this download by search term?

**Comment by JackLamber** [comment]
> 
> 
> Are you sure you selected the right service(redgifs when downloading from redgifs and gfycat when downloading from gfycat) and that you gave it the correct id (removed the @ when downloading from gfycat) or was this download by search term?

Yeah I'm pretty sure, I think maybe they changed something on their end.

**Comment by Quintkat** [comment]
Just wanted to chip in and further confirm it's an issue. I get the same error as JackLamber shared

**Comment by Nekromateion** [comment]
I've been trying around a bit and I never got the issue so far across ~25 users on both platforms which makes it kinda hard for me to debug this. But I'll try around more and hopefully I'll encounter the issue sometime.

**Comment by Quintkat** [comment]
oh huh, does the program need any special permissions enabled maybe? I ran it as administrator and it gave the same error. I also tried it with multiple different random users now and also a random smallish search term for good measure. None worked

**Comment by Nekromateion** [comment]
No the program doesn't need any special permissions. As long as it can write files and access the internet it should work.

Also thank you for that info this already helps me narrow down the causes for this error.

**Comment by Quintkat** [comment]
if you need any more info I could provide feel free to ask :>

**Comment by diffficult** [comment]
@Nekromateion could it be throttling or just blocking after you download all the content on a few users? I'll try to get it going under a different IP to see if it's something related to how they handle users and not the downloader itself.

**Comment by Nekromateion** [comment]
I have encountered rate limits before but only when running multiple instances of the application.

Additionally a rate limit would have the return code 429 not 404.

**Comment by Instagibz** [comment]
Just

**Comment by Instagibz** [comment]
Just fyi, some API endpoints are beeing changed atm.  See -> https://github.com/Redgifs/api/wiki

**Comment by Nekromateion** [comment]
Thanks for the info.
I didn't even know that that repo is a thing.

**Comment by JackLamber** [comment]
Any clue yet?

**Comment by Nekromateion** [comment]
I know what the issue is now problem is just that during the next two weeks I'm writing exams

**Comment by diffficult** [comment]
@Nekromateion no worries mate. Glad you know what stopped working. Good luck with the exams.

**Comment by Nekromateion** [comment]
gonna get to it next friday

**Comment by JackLamber** [comment]
> gonna get to it next friday

Great! BTW I have a suggestion if it's easy enough could you include a script that grab images?
Thank you for your work!

**Comment by JackLamber** [comment]
So how did your exams go?

**Comment by Nekromateion** [comment]
Fuck finally found some time to get to this.
Going to start the rewrite now expect a release in max 3 hours.

**Comment by Nekromateion** [comment]
Implemented downloading users from RedGifs in https://github.com/Nekromateion/RedGifs-Gfycat-Downloader/releases/tag/0.7 for now. That's all I'll do for today.
@JackLamber 
@diffficult 
@Quintkat

**Comment by Quintkat** [comment]
works great! thanks!

**Comment by JackLamber** [comment]
Thank you for taking your time to do this

**Comment by Nekromateion** [comment]
> Thank you for taking your time to do this
> 
> Edit: I'm on win 10 x64 and the exe closes immediately after opening it, I've tired both x64 and x86 and the same thing happens (also tried opening from command prompt and nothing happens). Am I doing something wrong?

You have to use the cli arguments now
I haven't added a menu to select stuff yet

**Comment by JackLamber** [comment]
> > Thank you for taking your time to do this
> > Edit: I'm on win 10 x64 and the exe closes immediately after opening it, I've tired both x64 and x86 and the same thing happens (also tried opening from command prompt and nothing happens). Am I doing something wrong?
> 
> You have to use the cli arguments now I haven't added a menu to select stuff yet

Oh boy what a tough learning curve... So I have to paste the exe path to cmd then paste the cli line after it? If so I get this error

`Downloading user (example)...
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GfycatDownloader_Rewrite_DNCore.RedGifs.DownloadUser(String userId, String type, Int32 minLikes)
   at GfycatDownloader_Rewrite_DNCore.Program.Main(String[] args)`

I'm sorry for bothering you but I'm just a Racecar Johnny end user, I appreciate your work but I'm kinda lost and the guides I've read aren't very helpful

**Comment by JackLamber** [comment]
> you need to pass the options as arguments when running the .exe the first time

See that's what's confusing me. I'm not sure how to do that. I can't open the exe as it closes immediately after opening it, same if I ran it as admin. I get that I need to run this line `RedGifs_Rewrite_DNCore_x64.exe --type=mp4 --user=jacklamber --minLikes=1` but I'm not sure exactly where to put it. If I paste the exe path followed by `RedGifs_Rewrite_DNCore_x64.exe --type=mp4 --user=jacklamber --minLikes=1` with a space between them in command prompt I get the error I mentioned above. Bare with me I have zero programming knowledge I just want to use this tool

**Comment by Nekromateion** [comment]
Hey there,
I recently found out that [Gallery-DL](https://github.com/mikf/gallery-dl) supports redgifs so please use that, since I don't have the time to maintain this project anymore.
